export const GET_WEATHER = "GET_WEATHER";
export const GET_WEATHER_FULFILLED = "GET_WEATHER_FULFILLED";
export const GET_WEATHER_REJECTED = "GET_WEATHER_REJECTED";
export const UPDATE_WEATHER_FULFILLED = "UPDATE_WEATHER_FULFILLED";
export const UPDATE_WEATHER = "UPDATE_WEATHER";
export const DELETE_WETHER = "DELETE_WETHER";
export const DELETE_WETHER_FULFILLED = "DELETE_WETHER_FULFILLED";
export const SET_IS_ERROR = "SET_IS_ERROR";
